version: "3"
services:
  web:
    build: web
    image: mateusgoto01/tripmeal-web:1.0
    environment:
      - DATABASE_NAME=tripmealdb
      - DATABASE_USER=root
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - TRIPMEAL_KEY='my-secret-key'
      - SERVER_PORT=5000
    networks:
      - backend
    ports:
      - 3000:5000
    
  db:
    build: database
    image: mateusgoto01/tripmeal-db:1.0
    networks:
      - backend
    ports:
      - 3306
    volumes:
      - trip-meal-data:/var/lib/mysql

networks:
  backend:

volumes:
  trip-meal-data: